export const GET_GAMES = "GET_GAMES";
export const SWITCH_ORDER_STATE = "SWITCH_ORDER_STATE";
export const SWITCH_ITEM_ORDER_STATE = "SWITCH_ITEM_ORDER_STATE";
export const SET_BASKET_SIZE = "SET_BASKET_SIZE";
